currency: ILS
adults: 2

route:
  origin: TLV
  destination: HKT

  # אתה משנה רק את זה:
  depart_center_date: "2025-12-20"

  # שבועיים קדימה/אחורה
  depart_window_days: 15

  # אל תשנה — הקוד מחשב אוטומטית
  return_center_date: "AUTO"
  return_window_days: "AUTO"

  # סף התראה (החיפוש עצמו לא תלוי בזה)
  max_price: 999999

  # בלי סינון חברת תעופה (בדיקה של כל החברות)
  # airline: ""

  # שהייה מינ'/מקס'
  min_stay_days: 11
  max_stay_days: 14
