currency: ILS
adults: 2

route:
  origin: TLV
  destination: JFK

  # יציאה: תאריך מרכזי וטווח ±ימים
  depart_center_date: "2025-11-20"
  depart_window_days: 3

  # חזרה: תאריך מרכזי וטווח ±ימים
  return_center_date: "2025-12-05"
  return_window_days: 3

  # סף למחיר כולל (הלוך+חזור) במטבע למעלה
  max_price: 2300

  # סינון לפי חברת תעופה (השאר ריק "" אם לא צריך)
  airline: LY

  # אילוץ שהייה מינימלית/מקסימלית (ימים)
  min_stay_days: 1
  max_stay_days: 30
