currency: ILS
adults: 2

route:
  origin: TLV
  destination: HKT   # פוקט (Phuket). קוד IATA לעיר/שדה: HKT

  # יציאה: תאריך מרכזי וטווח ±ימים
  depart_center_date: "2025-12-20"
  depart_window_days: 2

  # חזרה: תאריך מרכזי וטווח ±ימים
  return_center_date: "2025-05-30"
  return_window_days: 2

  # סף להתראה (החיפוש עצמו לא תלוי בזה)
  max_price: 999999

  # בלי סינון חברת תעופה (בדיקה של כל החברות)
  # airline: ""

  # אילוץ שהייה מינ'/מקס' (ימים)
  min_stay_days: 11
  max_stay_days: 14
