currency: ILS
adults: 1

route:
  origin: LON
  destination: NYC

  depart_center_date: "2025-10-15"
  depart_window_days: 1

  return_center_date: "2025-10-22"
  return_window_days: 1

  max_price: 999999
  # airline: ""   # בלי סינון

  min_stay_days: 1
  max_stay_days: 30
