currency: ILS
adults: 2
route:
  origin: TLV
  destination: HKT
  depart_center_date: '2026-02-15'
  depart_window_days: 15
  return_center_date: AUTO
  return_window_days: AUTO
  max_price: 999999.0
  min_stay_days: 11
  max_stay_days: 14
  airline: null
