currency: ILS
adults: 2

route:
  origin: TLV
  destination: HKT

  # יציאה: תאריך מרכזי וטווח ±ימים
  depart_center_date: "2026-01-08"
  depart_window_days: 3

  # חזרה: תאריך מרכזי וטווח ±ימים
  return_center_date: "2026-01-18"
  return_window_days: 3

  # סף למחיר כולל (הלוך+חזור) במטבע למעלה
  max_price: 7000

  # סינון לפי חברת תעופה (השאר ריק "" אם לא צריך)
  airline: LY

  # אילוץ שהייה מינימלית/מקסימלית (ימים)
  min_stay_days: 11
  max_stay_days: 14
