name: flight-alert-schedule

on:
  schedule:
    - cron: "0 4 * * *"   # פעם ביום ב-00:00 UTC
  workflow_dispatch: {}    # מאפשר להריץ ידנית

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot (generate results.json + history.json)
        env:
          AMADEUS_ENV: ${{ secrets.AMADEUS_ENV }} # השאר ריק/לא להגדיר = TEST; להגדיר ל-"prod" אם צריך פרודקשן
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
        run: python main.py

      - name: Prepare static site (dist)
        run: |
          mkdir -p dist
          cp -r site/* dist/
          cp results.json dist/  || echo '{"error":"no results.json"}' > dist/results.json
          cp history.json dist/  || echo '[]' > dist/history.json
          echo "✅ dist prepared:"
          ls -la dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
