name: flight-alert-schedule

on:
  schedule:
    - cron: "0 */2 * * *"   # רץ כל שעתיים (ב-UTC)
  workflow_dispatch: {}      # כפתור להרצה ידנית

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Debug workspace
        run: |
          echo "Python version:" && python --version
          echo "Repo files:" && ls -la
          echo "Show config.yaml exists:" && [ -f config.yaml ] && echo OK || echo MISSING
          echo "Env flags (לא הערכים!):"
          for v in EMAIL_HOST EMAIL_PORT EMAIL_USER EMAIL_PASS EMAIL_TO AMADEUS_API_KEY AMADEUS_API_SECRET; do
            if [ -z "${{ secrets[$v] || '' }}" ]; then
              echo "❌ secret $v is NOT set"
            else
              echo "✅ secret $v is set"
            fi
          done
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run main.py
        run: python main.py
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
