name: Run Flight Alert (cron)

on:
  schedule:
    - cron: "0 4 * * *"   # דוגמה: כל יום 07:00 Asia/Jerusalem ≈ 04:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AMADEUS_ENV: test
      # מיפוי מה-Secrets הקיימים אצלך אל שמות שהקוד קורא
      AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_API_KEY }}
      AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
    steps:
      - uses: actions/checkout@v4

      # בדיקת נוכחות לפני הריצה (לא חושף ערכים)
      - name: Debug env presence
        run: |
          python - << 'PY'
          import os
          print("AMADEUS_CLIENT_ID present:", bool(os.getenv("AMADEUS_CLIENT_ID")))
          print("AMADEUS_CLIENT_SECRET present:", bool(os.getenv("AMADEUS_CLIENT_SECRET")))
          print("AMADEUS_ENV:", os.getenv("AMADEUS_ENV"))
          PY

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python main.py
